user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    access_log /var/log/nginx/access.log;
    resolver 127.0.0.11 valid=10s ipv6=off;
    keepalive_timeout 0;
    server_tokens off;

    upstream tjarepo_backend {
        server tjarepo:8090;
    }

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    proxy_http_version 1.1;
    proxy_set_header Connection close;
    proxy_hide_header Host;
    proxy_hide_header X-Powered-By;
    proxy_hide_header Cache-Control;
    proxy_hide_header Expires;
    proxy_hide_header Pragma;

    server {
        listen 443 ssl default_server;
        server_name _;

        ssl_certificate     /certificates/local/server.crt;
        ssl_certificate_key /certificates/local/server.key;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://tjarepo_backend;
        }
    }
}
